# Site settings
title: Amos's blog
email: amos.doan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Welcome to Amos's blog
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
github_username: amosdoan 

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
gems:
  - jekyll-paginate
paginate: 15
paginate_path: "/blog/page:num/"

#collections:
#  portfolio:
#    output: true
#    permalink: /portfolio/:path/
#  poetry:
#    output: true
#    permalink: /poetry/:path/

